### PR TITLE
ci: Set up GitHub Actions

### PR DESCRIPTION
**Pull request by barbeau**
This will enable GitHub to run CI builds on every PR.

### CODE REVIEW

**Comment by barbeau** [comment]
Hmmm, looks like this is failing with:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.160 s
[INFO] Finished at: 2021-02-24T20:46:45Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (compile) on project gnss-ride-hailing-analyzer: Fatal error compiling: invalid target release: 15 -> [Help 1]
Error:  
```

...due to this in the pom.xml, which I don't think we need?

```
            <configuration>
                <source>15</source>
                <target>15</target>
            </configuration>
```

**Comment by BumbleFlash** [comment]
@barbeau I'm using jdk `15.0.2` to build the project locally and the `workflow` file uses JDK `1.8`. This seems like a possible reason why the CI would fail. Should I change the JDK version locally and can we make the CI use the version `15`

**Comment by barbeau** [comment]
Unless there is a specific reason to use JDK 15 (features introduced in later Java versions, dependencies that require later JDK versions), we should try and stick to JDK 8 or 9 for compatibility reasons.

Can you try reverting everything in pom.xml back to 1.8 instead of 15 and see if that works?

**Comment by barbeau** [comment]
For example, right now I can't clone and run this project on my machine because I don't have JDK 15 installed (even though I have JDK 8, 9, and 11). I get:

image

**Comment by BumbleFlash** [comment]
@barbeau I can install JDK `1.8` in the system and change the Java environmental path to the same. I think the module would work if no external modules depend on it.

**Comment by BumbleFlash** [comment]
@barbeau  Yay!

**Review by BumbleFlash — APPROVED** [review]

**Comment by barbeau** [comment]
Thanks @BumbleFlash! This works for me locally now too 👍 .

**Pull request merged**
